/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.staff.returnOrder;

import view.staff.sell.*;
import dto.BatchDTO;
import entity.UnitDetail;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JSpinner;
import util.MessageDialog;
import java.util.List;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Hoang
 */
public class PnSelectBatchReturn extends javax.swing.JPanel {

    /**
     * Creates new form PnLo
     */
    private BatchDTO batchDTO;
    private UnitDetail unitDetail;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private JSpinner jSpinner;
    private final int maxQuantity;

    public PnSelectBatchReturn() {
        initComponents();
        maxQuantity = 0;
    }

    public JSpinner getSpinnerQuantity() {
        return spinnerQuantity;
    }

    public PnSelectBatchReturn(BatchDTO batchDTO, UnitDetail unitDetail, JSpinner jSpinner) {
        initComponents();
        this.batchDTO = batchDTO;
        this.unitDetail = unitDetail;
        this.jSpinner = jSpinner;
        spinnerQuantity.setValue(batchDTO.getQuantity());

        maxQuantity = batchDTO.getQuantity();
        ((SpinnerNumberModel) spinnerQuantity.getModel()).setMaximum(maxQuantity);
        setName();
    }

    public void setName() {
        String name = batchDTO.getName() + " - " + formatter.format(batchDTO.getExpirationDate())
                + " - SL: " + maxQuantity + " - Trả: " + batchDTO.getQuantity();
        txtBatch.setText(name);
    }

    public UnitDetail getUnitDetail() {
        return unitDetail;
    }

    public void setUnitDetail(UnitDetail unitDetail) {
        this.unitDetail = unitDetail;
    }

    public BatchDTO getBatchDTO() {
        return batchDTO;
    }

    public void setBatchDTO(BatchDTO batchDTO) {
        this.batchDTO = batchDTO;
    }

    public JSpinner getjSpinner() {
        return jSpinner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalSoLuong = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        txtExpirationDate = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        spinnerQuantity = new javax.swing.JSpinner();
        btnConfirmModal = new javax.swing.JButton();
        txtMaxQuantiy = new javax.swing.JLabel();
        txtBatch = new javax.swing.JLabel();

        modalSoLuong.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalSoLuong.setBackground(new java.awt.Color(255, 255, 255));
        modalSoLuong.setMinimumSize(new java.awt.Dimension(518, 300));
        modalSoLuong.setModal(true);
        modalSoLuong.setPreferredSize(new java.awt.Dimension(518, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(518, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(518, 300));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Lô");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 204, 204));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtName.setToolTipText("");
        txtName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExpirationDate.setText("Hạn sử dụng");

        txtExpirationDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtExpirationDate.setForeground(new java.awt.Color(204, 204, 204));
        txtExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtExpirationDate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtExpirationDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantity.setText("Số lượng");

        spinnerQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        spinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spinnerQuantity.setFocusable(false);
        spinnerQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerQuantityStateChanged(evt);
            }
        });

        btnConfirmModal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmModal.setText("Xác nhận");
        btnConfirmModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmModalActionPerformed(evt);
            }
        });

        txtMaxQuantiy.setBackground(new java.awt.Color(255, 255, 255));
        txtMaxQuantiy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaxQuantiy.setText("/ 10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfirmModal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExpirationDate)
                            .addComponent(lblQuantity)
                            .addComponent(lblName))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaxQuantiy, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(30, 30, 30)
                        .addComponent(lblExpirationDate)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuantity)
                        .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMaxQuantiy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmModal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modalSoLuongLayout = new javax.swing.GroupLayout(modalSoLuong.getContentPane());
        modalSoLuong.getContentPane().setLayout(modalSoLuongLayout);
        modalSoLuongLayout.setHorizontalGroup(
            modalSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalSoLuongLayout.setVerticalGroup(
            modalSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(3, 130, 193));

        txtBatch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBatch.setForeground(new java.awt.Color(255, 255, 255));
        txtBatch.setText("jLabel1");
        txtBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBatchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBatch, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBatch)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBatchMouseClicked
        txtName.setText(batchDTO.getName());
        txtExpirationDate.setText(formatter.format(batchDTO.getExpirationDate()));
        txtMaxQuantiy.setText(" / " + maxQuantity);

        modalSoLuong.setTitle(batchDTO.getName() + " - " + formatter.format(batchDTO.getExpirationDate()));
        modalSoLuong.setLocationRelativeTo(null);
        modalSoLuong.setVisible(true);

    }//GEN-LAST:event_txtBatchMouseClicked

    private void btnConfirmModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmModalActionPerformed
        // TODO add your handling code here:
        modalSoLuong.dispose();
        int quantity = (int) spinnerQuantity.getValue();
        jSpinner.setValue((int) jSpinner.getValue() - batchDTO.getQuantity() + quantity);

        Container parent = this.getParent();
        for (Component component : parent.getComponents()) {
            if (component instanceof PnSelectBatchReturn) {
                PnSelectBatchReturn pnSelectBatch = (PnSelectBatchReturn) component;
                if (pnSelectBatch.getBatchDTO().getName().equals(batchDTO.getName())) {
                    pnSelectBatch.getBatchDTO().setQuantity(quantity);
                }
            }
        }

        String name = batchDTO.getName() + " - " + formatter.format(batchDTO.getExpirationDate())
                + " - SL: " + maxQuantity + " - Trả: " + batchDTO.getQuantity();
        txtBatch.setText(name);

        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_btnConfirmModalActionPerformed

    
    
    private void spinnerQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerQuantityStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_spinnerQuantityStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmModal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JDialog modalSoLuong;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JLabel txtBatch;
    private javax.swing.JLabel txtExpirationDate;
    private javax.swing.JLabel txtMaxQuantiy;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
