/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.common;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import util.ResizeImage;

/**
 *
 * @author Hoang
 */
public class PanelActionReturnManage extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelActionReturnManage() {
        initComponents();
        returnedBtn();
        damagedBtn();
    }

    public void initEvent(TableActionEventReturnManage event, int row) {
        returned.addActionListener((ActionEvent ae) -> {
            event.onReturned(row);
        });

        damaged.addActionListener((ActionEvent ae) -> {
            event.onDamaged(row);
        });
    }

    public void returnedBtn() {
        returned.setBackground(new java.awt.Color(44, 208, 44));
        returned.setForeground(Color.BLACK);
        returned.setIcon(ResizeImage.resizeImage(new FlatSVGIcon(getClass().getResource("/img/addBtn.svg")), 27, 27));
        
    }

    // Phương thức để đặt màu cho nút 'damaged'
    public void damagedBtn() {
        damaged.setBackground(new java.awt.Color(255, 51, 51));
        damaged.setForeground(Color.BLACK);
        damaged.setIcon(ResizeImage.resizeImage(new FlatSVGIcon(getClass().getResource("/img/deleteBtn.svg")), 27, 27));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returned = new gui.common.ActionButton();
        damaged = new gui.common.ActionButton();

        returned.setBackground(new java.awt.Color(51, 255, 51));
        returned.setForeground(new java.awt.Color(255, 255, 255));

        damaged.setBackground(new java.awt.Color(255, 51, 51));
        damaged.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(returned, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(damaged, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returned, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(damaged, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.common.ActionButton damaged;
    private gui.common.ActionButton returned;
    // End of variables declaration//GEN-END:variables
}
