/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.manager;

import com.formdev.flatlaf.FlatClientProperties;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import util.ResizeImage;

/**
 *
 * @author Hoang
 */
public class PnUnitSelect extends javax.swing.JPanel {

    /**
     * Creates new form PnUnitSelect
     */
    private boolean isDefault;
    private TABProduct tabProduct;
    private String selectPrevious;
    private int type;

    public PnUnitSelect() {
        initComponents();

        comboUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Đơn vị tính");
        txtRate.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Giá trị quy đổi");
    }

    public PnUnitSelect(List<String> unitNames, boolean isDefault, TABProduct tabProduct, int type) {
        initComponents();
        fillComboUnit(unitNames);
        if (isDefault == false) {
            icon.setIcon(ResizeImage.resizeImage(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png")), 15, 15));
        } else {
            txtRate.setText("1");
            txtRate.setEditable(false);
        }
        this.isDefault = isDefault;
        this.type = type;
        this.tabProduct = tabProduct;
        comboUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Đơn vị tính");
        txtRate.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Giá trị quy đổi");
        this.selectPrevious = (String) comboUnit.getSelectedItem();
    }

    public void fillComboUnit(List<String> unitNames) {
        comboUnit.removeAllItems();
        for (String name : unitNames) {
            comboUnit.addItem(name);
        }
    }

    public boolean isIsDefault() {
        return isDefault;
    }

    public void setIsDefault(boolean isDefault) {
        this.isDefault = isDefault;
    }

    public JComboBox<String> getComboUnit() {
        return comboUnit;
    }

    public JTextField getTxtRate() {
        return txtRate;
    }

    public void setTxtRate(JTextField txtRate) {
        this.txtRate = txtRate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRate = new javax.swing.JTextField();
        comboUnit = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(343, 42));
        setMinimumSize(new java.awt.Dimension(343, 42));
        setPreferredSize(new java.awt.Dimension(343, 42));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(395, 42));
        jPanel1.setMinimumSize(new java.awt.Dimension(395, 42));

        txtRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        comboUnit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboUnit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUnitItemStateChanged(evt);
            }
        });

        icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(comboUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(txtRate, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMouseClicked
        if (type == 1) {
            tabProduct.removePnUnit(this);
        } else if (type == 2) {
            tabProduct.removePnUnitEdit(this);
        }
    }//GEN-LAST:event_iconMouseClicked

    private void comboUnitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUnitItemStateChanged


    }//GEN-LAST:event_comboUnitItemStateChanged

    private boolean ignoreSelectionChange = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboUnit;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
