/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.manager;

import bus.EmployeeBUS;
import entity.Employee;
import java.awt.Color;
import javax.swing.BorderFactory;
import view.login.LoadApplication;
import util.CurrentEmployee;

/**
 *
 * @author Hoang
 */
public class TABPersonalInformation extends javax.swing.JPanel {

    private final EmployeeBUS employeeBUS;
    private Employee employee = CurrentEmployee.getEmployee();

    public TABPersonalInformation() {
        employeeBUS = LoadApplication.employeeBUS;
        initComponents();
        fillContent();
    }
    
    private void fillContent() {
        txtMa.setText(employee.getEmployeeId());
        txtTen.setText(employee.getName());
        txtDiaChi.setText(employee.getAddress());
        txtEmail.setText(employee.getEmail());
        txtSDT.setText(employee.getPhone());
        txtChucVu.setText(employee.getRole());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAll = new javax.swing.JPanel();
        pnRight = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnAll.setBackground(new java.awt.Color(255, 255, 255));

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRight.setMinimumSize(new java.awt.Dimension(1083, 765));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel42.setText("Họ và tên:");
        pnRight.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel44.setText("Số điện thoại:");
        pnRight.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel46.setText("Email:");
        pnRight.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel48.setText("Role:");
        pnRight.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel61.setText("Mã nhân viên:");
        pnRight.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel76.setText("Địa chỉ");
        pnRight.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        txtMa.setEditable(false);
        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMa.setRequestFocusEnabled(false);
        pnRight.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 420, 40));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setRequestFocusEnabled(false);
        pnRight.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 420, 40));

        txtTen.setEditable(false);
        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTen.setRequestFocusEnabled(false);
        pnRight.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 420, 40));

        txtSDT.setEditable(false);
        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSDT.setRequestFocusEnabled(false);
        pnRight.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 420, 40));

        txtChucVu.setEditable(false);
        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChucVu.setRequestFocusEnabled(false);
        pnRight.add(txtChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 420, 40));

        txtDiaChi.setEditable(false);
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDiaChi.setRequestFocusEnabled(false);
        pnRight.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 420, 40));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel43.setText("Thông tin cá nhân");

        javax.swing.GroupLayout pnAllLayout = new javax.swing.GroupLayout(pnAll);
        pnAll.setLayout(pnAllLayout);
        pnAllLayout.setHorizontalGroup(
            pnAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAllLayout.createSequentialGroup()
                .addGroup(pnAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAllLayout.createSequentialGroup()
                        .addGap(603, 603, 603)
                        .addComponent(jLabel43))
                    .addGroup(pnAllLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        pnAllLayout.setVerticalGroup(
            pnAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAllLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel43)
                .addGap(66, 66, 66)
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JPanel pnAll;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
