/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.staff.sell;

import java.time.format.DateTimeFormatter;
import entity.Batch;
/**
 *
 * @author daoducdanh
 */
public class PnSelectBatch extends javax.swing.JPanel {

    /**
     * Creates new form PnLo
     */
    private Batch batch;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private int quantity;
    
    public PnSelectBatch() {
        initComponents();
    }
    
    public PnSelectBatch(Batch batch, int quantity){
        initComponents();
        this.batch = batch;
        this.quantity = quantity;
        
        String name = batch.getName() + " - " + formatter.format(batch.getExpirationDate())
                    + " - SL: " + quantity;
        txtBatch.setText(name);
    }

    public Batch getBatch() {
        return batch;
    }

    public int getQuantity() {
        return quantity;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBatch = new javax.swing.JLabel();

        setBackground(new java.awt.Color(3, 130, 193));

        txtBatch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBatch.setForeground(new java.awt.Color(255, 255, 255));
        txtBatch.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBatch, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBatch)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtBatch;
    // End of variables declaration//GEN-END:variables
}
